defaults:
  nicks: 
    - "{{{TEMP_MAIN_IRC_NICKNAME}}}"
  realname: "{{{TEMP_MAIN_IRC_REALNAME}}}"
log_dir: "{{{home_dir}}}/.cache/tiny"    
servers:
  - addr: irc.ea.libera.chat
    port: 7000
    realname: "{{{TEMP_MAIN_IRC_REALNAME}}}"
    nickserv_ident: NickServ
    nicks: 
      - "{{{TEMP_MAIN_IRC_NICKNAME}}}"
    sasl:
      username: '{{{TEMP_MAIN_IRC_NICKNAME}}}'
      password: '{{{TEMP_MAIN_IRC_PASSWORD}}}'      
    tls: true
    join:
      - '#alacritty'
      - '#bash'
      - '#javascript'
      - '#kakoune'
      - '#tmux'
      - '#libera'