evaluate-commands %sh{
    config_files="
        tmux-repl.kak
        plugins.kak
        buffer-switcher.kak
        commands.kak
        common.kak
        connect.kak
    "
    for file in $config_files; do
        printf "%s" "
            try %{
                source %{${kak_config:?}/includes/$file}
            } catch %{
                echo -debug %val{error}
            }
        "
    done
    [ -f $kak_config/local.kak ] && echo "source $kak_config/local.kak"

}
try %{ source .kakrc.local }
